if dat == nil then dat = {} end
if dat.flags == nil then dat.flags = {} end
dat.flags.anim = {
    { value = (1<<0), name = "AF_LOOPING", note = "Loop the animation" },
    { value = (1<<1), name = "AF_HOLD_LAST_FRAME", note = "Stop animation on last frame" },
    { value = (1<<2), name = "AF_NOT_INTERRUPTABLE", note = "Prevent animation interrupts" },
    { value = (1<<3), name = "AF_UPPERBODY", note = "Filter animation to upper body" },
    { value = (1<<4), name = "AF_SECONDARY", note = "Allow player control" },
    { value = (1<<5), name = "AF_ABORT_ON_PED_MOVEMENT", note = "Abort animation on movement" },
    { value = (1<<6), name = "AF_ADDITIVE", note = "Used for additive animations" },
    { value = (1<<7), name = "AF_OVERRIDE_PHYSICS", note = "" },
    { value = (1<<8), name = "AF_EXTRACT_INITIAL_OFFSET", note = "" },
    { value = (1<<9), name = "AF_EXIT_AFTER_INTERRUPTED", note = "" },
    { value = (1<<10), name = "AF_TAG_SYNC_IN", note = "" },
    { value = (1<<11), name = "AF_TAG_SYNC_OUT", note = "" },
    { value = (1<<12), name = "AF_TAG_SYNC_CONTINUOUS", note = "" },
    { value = (1<<13), name = "AF_FORCE_START", note = "" },
    { value = (1<<14), name = "AF_USE_KINEMATIC_PHYSICS", note = "" },
    { value = (1<<15), name = "AF_USE_MOVER_EXTRACTION", note = "" },
    { value = (1<<16), name = "AF_DONT_SUPPRESS_LOCO", note = "" },
    { value = (1<<17), name = "AF_ENDS_IN_DEAD_POSE", note = "" },
    { value = (1<<18), name = "AF_ACTIVATE_RAGDOLL_ON_COLLISION", note = "" },
    { value = (1<<19), name = "AF_DONT_EXIT_ON_DEATH", note = "" },
    { value = (1<<20), name = "AF_ABORT_ON_WEAPON_DAMAGE", note = "" },
    { value = (1<<21), name = "AF_DISABLE_FORCED_PHYSICS_STATE", note = "" },
    { value = (1<<22), name = "AF_GESTURE", note = "Used for gesture type animations" },
    { value = (1<<23), name = "AF_SKIP_IF_BLOCKED_BY_HIGHER_PRIORITY_TASK", note = "" },
    { value = (1<<24), name = "AF_USE_ABSOLUTE_MOVER", note = "" },
    { value = (1<<25), name = "AF_0xC57F16E7", note = "" },
    { value = (1<<26), name = "AF_UPPERBODY_TAGS", note = "Disables lower spine. Only works with taskfilter false" },
    { value = (1<<27), name = "AF_PROCESS_ATTACHMENTS_ON_START", note = "" },
    { value = (1<<28), name = "AF_EXPAND_PED_CAPSULE_FROM_SKELETON", note = "" },
    { value = (1<<29), name = "AF_BLENDOUT_WRT_LAST_FRAME", note = "" },
    { value = (1<<30), name = "AF_DISABLE_PHYSICAL_ACTIVATION", note = "" },
    { value = (1<<31), name = "AF_DISABLE_RELEASE_EVENTS", note = "" },
    -- { value = (1<<32), name = "AF_0x70F38514", note = "" },
    -- Combo Flags
    -- { value = (1<<3)|(1<<4), name = "AF_UPPERBODY, AF_SECONDARY" },
    -- { value = (1<<0)|(1<<3)|(1<<4), name = "AF_LOOPING, AF_UPPERBODY, AF_SECONDARY" },
}
