if dat == nil then dat = {} end
if dat.flags == nil then dat.flags = {} end
dat.flags.anim = {
    { value = (1<<0), name = "AF_LOOPING" },
    { value = (1<<1), name = "AF_HOLD_LAST_FRAME" },
    { value = (1<<2), name = "AF_NOT_INTERRUPTABLE" },
    { value = (1<<3), name = "AF_UPPERBODY" },
    { value = (1<<4), name = "AF_SECONDARY" },
    { value = (1<<5), name = "AF_ABORT_ON_PED_MOVEMENT" },
    { value = (1<<6), name = "AF_ADDITIVE" },
    { value = (1<<7), name = "AF_OVERRIDE_PHYSICS" },
    { value = (1<<8), name = "AF_EXTRACT_INITIAL_OFFSET" },
    { value = (1<<9), name = "AF_EXIT_AFTER_INTERRUPTED" },
    { value = (1<<10), name = "AF_TAG_SYNC_IN" },
    { value = (1<<11), name = "AF_TAG_SYNC_OUT" },
    { value = (1<<12), name = "AF_TAG_SYNC_CONTINUOUS" },
    { value = (1<<13), name = "AF_FORCE_START" },
    { value = (1<<14), name = "AF_USE_KINEMATIC_PHYSICS" },
    { value = (1<<15), name = "AF_USE_MOVER_EXTRACTION" },
    { value = (1<<16), name = "AF_DONT_SUPPRESS_LOCO" },
    { value = (1<<17), name = "AF_ENDS_IN_DEAD_POSE" },
    { value = (1<<18), name = "AF_ACTIVATE_RAGDOLL_ON_COLLISION" },
    { value = (1<<19), name = "AF_DONT_EXIT_ON_DEATH" },
    { value = (1<<20), name = "AF_ABORT_ON_WEAPON_DAMAGE" },
    { value = (1<<21), name = "AF_DISABLE_FORCED_PHYSICS_STATE" },
    { value = (1<<22), name = "AF_GESTURE" },
    { value = (1<<23), name = "AF_SKIP_IF_BLOCKED_BY_HIGHER_PRIORITY_TASK" },
    { value = (1<<24), name = "AF_USE_ABSOLUTE_MOVER" },
    { value = (1<<25), name = "AF_0xC57F16E7" },
    { value = (1<<26), name = "AF_UPPERBODY_TAGS" },
    { value = (1<<27), name = "AF_PROCESS_ATTACHMENTS_ON_START" },
    { value = (1<<28), name = "AF_EXPAND_PED_CAPSULE_FROM_SKELETON" },
    { value = (1<<29), name = "AF_BLENDOUT_WRT_LAST_FRAME" },
    { value = (1<<30), name = "AF_DISABLE_PHYSICAL_ACTIVATION" },
    { value = (1<<31), name = "AF_DISABLE_RELEASE_EVENTS" },
    -- { value = (1<<32), name = "AF_0x70F38514" },
    -- Combo Flags
    -- { value = (1<<3)|(1<<4), name = "AF_UPPERBODY, AF_SECONDARY" },
    -- { value = (1<<0)|(1<<3)|(1<<4), name = "AF_LOOPING, AF_UPPERBODY, AF_SECONDARY" },
}
