if dat == nil then dat = {} end
dat.taskFilter = {
    { value = "", name = "None", note = "Prevents some AnimFlags from working??" },
    { value = "accessoriesonly_filter", name = "Accessories Only", note = "Animate Accessories Only" },
    { value = "allfingers_and_hand_helpers_filter", name = "Helper: Fingers, Hands", note = "" },
    { value = "allfingers_and_hand_helpers_no_ch_filter", name = "Helper: Fingers, Hands (no ch)", note = "" },
    { value = "allfingers_and_toes_and_hand_helpers_filter", name = "Helper: Fingers, Toes, Hands", note = "" },
    { value = "arm_l_and_hat", name = "Left Arm, Hat", note = "Only animate left arm and hat" },
    { value = "arms_filter", name = "Arms", note = "Only animate arms" },
    { value = "armsheadnomover_filter", name = "No Move: Arms, Head", note = "" },
    { value = "biped_capture_filter", name = "Biped Capture", note = "" },
    { value = "bodyonly_filter", name = "Body", note = "Only animate body" },
    { value = "bonemask_armonly_l", name = "Bone Mask: Left Arm", note = "" },
    { value = "bonemask_armonly_r", name = "Bone Mask: Right Arm", note = "" },
    { value = "bonemask_arms", name = "Bone Mask: Arms", note = "" },
    { value = "bonemask_bodyonly", name = "Bone Mask: Body", note = "" },
    { value = "bonemask_head_neck_and_arms", name = "Bone Mask: Head, Neck, Arms", note = "" },
    { value = "bonemask_head_neck_and_l_arm", name = "Bone Mask: Head, Neck, Left Arm", note = "" },
    { value = "bonemask_head_neck_and_r_arm", name = "Bone Mask: Head, Neck, Right Arm", note = "" },
    { value = "bonemask_headonly", name = "Bone Mask: Head", note = "" },
    { value = "bonemask_lod_lo", name = "Bone Mask: LOD", note = "" },
    { value = "bonemask_spine_feathered", name = "Bone Mask: Feather Spine", note = "" },
    { value = "bonemask_spineonly", name = "Bone Mask: Spine", note = "" },
    { value = "bonemask_upperonly", name = "Bone Mask: Upper Body", note = "" },
    { value = "botharms_filter", name = "Both Arms", note = "Don't animate arms?" },
    { value = "botharms_nospine_filter", name = "No Spine", note = "" },
    { value = "ch_only_filter", name = "CH Only", note = "" },
    { value = "corebones", name = "Core Bones", note = "" },
    { value = "facial_and_handik_filter", name = "Facial, Hand IK", note = "" },
    { value = "facial_and_mhmask_filter", name = "Facial, MHMask", note = "" },
    { value = "facialcapture_filter", name = "Facial Capture", note = "" },
    { value = "facialonly_brows", name = "Eyebrows Only", note = "" },
    { value = "facialonly_dialogue", name = "Dialogue Only", note = "" },
    { value = "facialonly_filter", name = "Face Only", note = "" },
    { value = "facialonly_mouth", name = "Mouth Only", note = "" },
    { value = "facingonly_filter", name = "Facing Only", note = "" },
    { value = "fps_camera_only_filter", name = "FPS Camera", note = "" },
    { value = "grip_l_only_filter", name = "Grip Left", note = "" },
    { value = "grip_l_only_no_ch_filter", name = "Grip Left (no ch)", note = "" },
    { value = "grip_l_only_no_ch_no_ik_filter", name = "Grip Left (no ch, no ik)", note = "" },
    { value = "grip_r_only_filter", name = "Grip Right", note = "" },
    { value = "grip_r_only_no_ch_filter", name = "Grip Right (no ch)", note = "" },
    { value = "grip_r_only_no_ch_no_ik_filter", name = "Grip Right (no ch, no ik)", note = "" },
    { value = "grip_r_only_no_ik_hand_helpers_filter", name = "Grip Right (no ik, hand helpers)", note = "" },
    { value = "headandneckonly_filter", name = "Head, Neck", note = "" },
    { value = "headandneckonly_no_fp_camera_filter", name = "Head, Neck (No FP)", note = "" },
    { value = "headneckandarms_filter", name = "Head, Neck, Arms", note = "" },
    { value = "headneckandleftarm_filter", name = "Head, Neck, Left Arm", note = "" },
    { value = "headneckandrightarm_filter", name = "Head, Neck, Right Arm", note = "" },
    { value = "headonly_filter", name = "Head", note = "" },
    { value = "horse_capture_filter", name = "Horse Capture", note = "" },
    { value = "horse_head_and_neck", name = "Horse Head, Neck", note = "" },
    { value = "ignoremoverblend_filter", name = "No Mover Blend", note = "" },
    { value = "ignoremoverblendrotationonly_filter", name = "No Mover Blend, Rotate Only", note = "" },
    { value = "ignoreohmoverblend_filter", name = "Ignore oh Mover Blend", note = "" },
    { value = "ik_recoil_l_filter", name = "IK Recoil Left", note = "" },
    { value = "ik_recoil_oh_filter", name = "IK Recoil OH", note = "" },
    { value = "ik_recoil_oh_transitionmultiplier", name = "IK Recoil OH Multix", note = "" },
    { value = "ik_recoil_r_filter", name = "IK Recoil Right", note = "" },
    { value = "ik_recoil_reload_both_hands_filter", name = "IK Recoil Reload Hands", note = "" },
    { value = "jacketonly_filter", name = "Jacket", note = "" },
    { value = "leftarm_nospine_filter", name = "Left Arm, No Spine", note = "" },
    { value = "leftarmonly_filter", name = "Left Arm Only", note = "" },
    { value = "leftfingers_and_helpers_filter", name = "Left Fingers, Helpers", note = "" },
    { value = "leftfingers_and_helpers_noik_filter", name = "Left Fingers, Helpers, No IK", note = "" },
    { value = "lefthand_fingers_filter", name = "Left Hand, Fingers", note = "" },
    { value = "lefthandik_and_fps_camera_filter", name = "Left Hand IK, FP Cam", note = "" },
    { value = "lefthandik_only_filter", name = "Left Hand, IK Only", note = "" },
    { value = "leftlegonly_filter", name = "Left Leg Only", note = "" },
    { value = "legsonly_filter", name = "Legs Only", note = "" },
    { value = "lolod_filter", name = "Lo LOD", note = "" },
    { value = "lookcontrol_and_handik_filter", name = "Look Control, Hand IK", note = "" },
    { value = "lookcontrol_only_filter", name = "Look Control Only", note = "" },
    { value = "lowerbody_filter", name = "Lowerbody", note = "" },
    { value = "mh_mask_and_ch_filter", name = "MH Mask, CH", note = "" },
    { value = "mh_mask_and_leftfingers_filter", name = "MH Mask, Left Fingers", note = "" },
    { value = "mh_mask_and_lefthandik_filter", name = "MH Mask, Left Hand IK", note = "" },
    { value = "mh_mask_and_righthandik_filter", name = "MH Mask, Right Hand IK", note = "" },
    { value = "mh_maskonly_filter", name = "MH Mask Only", note = "" },
    { value = "moveronly_filter", name = "Mover Only", note = "" },
    { value = "no_ph_l_carriable_filter", name = "No Prop Hand Left Carriable", note = "" },
    { value = "nofirstpersoncamera_filter", name = "No FP Cam", note = "" },
    { value = "noleftarm_filter", name = "No Left Arm", note = "" },
    { value = "nolefthand_filter", name = "No Left Hand", note = "" },
    { value = "noleftleg_filter", name = "No Left Leg", note = "" },
    { value = "nomover_filter", name = "No Mover", note = "" },
    { value = "norightarm_filter", name = "No Right Arm", note = "" },
    { value = "norighthand_filter", name = "No Right Hand", note = "" },
    { value = "norighthand_with_ik_filter", name = "No Right Hand, IK", note = "" },
    { value = "norightleg_filter", name = "No Right Leg", note = "" },
    { value = "noroot_filter", name = "No Root", note = "" },
    { value = "null_filter", name = "Null", note = "" },
    { value = "oh_pelvis_only_filter", name = "OH Pelvis", note = "" },
    { value = "oh_torsodir_and_oh_facingdir_filter", name = "OH Torso Direction, OH Facing", note = "" },
    { value = "ph_r_carriableshoulder_only_filter", name = "Prop Right Carriable Shoulder Only", note = "" },
    { value = "ph_rifleinverted_and_ph_l_armpitrifle_only_filter", name = "Prop: Rifle Inverted, Armpit Rifle Only", note = "" },
    { value = "ph_spinelevel01_only_filter", name = "Prop: Spine 1 Only", note = "" },
    { value = "rightarm_nospine_filter", name = "Right Arm, No Spine", note = "" },
    { value = "rightarmonly_filter", name = "Right Arm Only", note = "" },
    { value = "rightfingers_and_helpers_filter", name = "Right Fingers, Helpers", note = "" },
    { value = "righthand_fingers_filter", name = "Right Hand, Fingers", note = "" },
    { value = "righthandik_and_fps_camera_filter", name = "Right Hand IK, FP Cam", note = "" },
    { value = "righthandik_only_filter", name = "Right Hand IK Only", note = "" },
    { value = "rightlegonly_filter", name = "Right Leg Only", note = "" },
    { value = "rootonly_filter", name = "Root Only", note = "" },
    { value = "rootupperbody_filter", name = "Root Upper Body", note = "" },
    { value = "satchel_and_hatloc_filter", name = "Satchel and Hat Location", note = "" },
    { value = "satchel_and_ik_hand_helpers_filter", name = "Satchel and IK Hand Helpers", note = "" },
    { value = "satchel_and_ik_hand_helpers_nocam_filter", name = "Satchel and IK Hand Helpers, No Cam", note = "" },
    { value = "satchel_and_ik_l_hand_helper_filter", name = "Satchel and IK Left Hand Helper", note = "" },
    { value = "satchel_and_ik_left_hand_helpers_nocam_filter", name = "Satchel and IK Left Hand Helper No Cam", note = "" },
    { value = "satchel_and_ph_hand_helpers_filter", name = "Satchel, Prop Hand Helpers", note = "" },
    { value = "satchel_only_filter", name = "Satchel Only", note = "" },
    { value = "spinefeathered_filter", name = "Spine Feathered", note = "" },
    { value = "spineonly_filter", name = "Spine Only", note = "" },
    { value = "taskbodyblendedentry_ignored_dofs_filter", name = "Blend Body, Ignore DOFs", note = "" },
    { value = "toes_filter", name = "Toes", note = "" },
    { value = "trunkonly_filter", name = "Trunk Only", note = "" },
    { value = "upperbody_filter", name = "Upperbody", note = "" },
    { value = "upperbody_from_spine3_filter", name = "Spine 3 Upperbody", note = "" },
    { value = "upperbodyandfacing_filter", name = "Upperbody, Facing", note = "" },
    { value = "upperbodyandik_filter", name = "Upperbody, IK", note = "" },
    { value = "upperbodybicycledriveby_filter", name = "Upperbody, Bicycle", note = "" },
    { value = "upperbodyfeathered_cover_filter", name = "Upperbody Feathered, Cover", note = "" },
    { value = "upperbodyfeathered_filter", name = "Upperbody Feathered", note = "" },
    { value = "upperbodyfeathered_noleftarm_partialhead_filter", name = "Upperbody Feathered, No Left Arm, Partial Head", note = "" },
    { value = "upperbodyfeathered_nolefttarm_filter", name = "Upperbody Feathered, No Left Arm", note = "" },
    { value = "upperbodyfeathered_norightarm_filter", name = "Upperbody Feathered, No Right Arm", note = "" },
    { value = "upperbodyfeathered_norightarm_partialhead_filter", name = "Upperbody Feathered, No Right Arm, Partial Head", note = "" },
    { value = "upperbodyfeathered_partialhead_filter", name = "Upperbody Feathered, Partial Head", note = "" },
    { value = "upperbodyfixup_filter", name = "Upperbody Fixup", note = "" },
    { value = "upperbodyfixupandfacing_filter", name = "Upperbody Fixup, Facing", note = "" },
    { value = "upperbodynoarms_filter", name = "Upperbody, No Arms", note = "" },
    { value = "upperbodynomover_filter", name = "Upperbody, No Mover", note = "" },
    { value = "upperbodywithsatchel_filter", name = "Upperbody, Satchel", note = "" },
    { value = "upperonly_filter", name = "Upper Only", note = "" },
    { value = "weaponswap_filter", name = "Weapon Swap", note = "" },
}

